### ISSUE TITLE
Lazy load twig extensions

### ISSUE THREAD

**Issue by Jupi007** [slope-it/breadcrumb-bundle#16]
Hi,
I noticed that the twig extension are not [lazy loaded](https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions).
Would you like a PR to implement that?

**Comment by asprega** [comment]
Hi! Interesting feature, I did not know about it.

It's definitely an interesting concept, but:

- I would need to bump Twig dependency from ^2.1 to ^2.4.4 (which is not necessarily a bad thing, but I'd like to do it if there are tangible advantages)
- it does seem to add some complexity and the documentation indicates that there's likely no impact when the dependencies injected do not need to do "slow" stuff.

As this is conceptually an extension that, if you're using breadcrumbs, would be used in almost all requests, I don't think we should add that complexity. No other bundles I use (nor extensions directly provided by Symfony) are doing this. I don't think making such a change would make any noticeable difference in real world scenario.

If you still think you need to do that, you can always re-define the service as [lazy](https://symfony.com/doc/current/service_container/lazy_services.html) yourself by adding `lazy: true` to the definition. Alternatively, you could use a [compiler pass](https://symfony.com/doc/current/service_container/compiler_passes.html) to do the same.

Would that be okay with you?

**Comment by Jupi007** [comment]
About the Twig dependency, this bundle already depends on the ^2.10 version: https://github.com/slope-it/breadcrumb-bundle/blob/aa931b085cbe66c9703942c26e77a4defd764a7d/composer.json#L28

But as you said the performance improvement is negligible .
It is only because I am used to do it in my projects that I have proposed it to you :)

**Comment by Jupi007** [comment]
I close this, because it could even deteriorate a bit the performance to implement that, as it require a bit more logic.

Anyway, I'm glad I taught you something interesting @asprega :)

**Comment by asprega** [comment]
Oh yeah, sorry I didn't follow up to your reply. You were right about the version number, for some reason my brain thought that 2.10 was less than 2.4.4 😂 

Of course, there's always something to learn. Thanks again for your contributions!
