### ISSUE TITLE
I need to use a dynamic route

### ISSUE THREAD

**Issue by 10YAR** [slope-it/breadcrumb-bundle#2]
Hello

I need to use a dynamic route like this: "route" = "$myRoute"

how can I do that ?

Thanks

**Comment by asprega** [comment]
Hi! You can do it by injecting the `BreadcrumbBuilder` and use the `addItem` method directly in the controller and not use the annotations.

I'll update the documentation to illustrate this use case.
Closing this issue, feel free to re-open in case you need it.

Thanks!
