### ISSUE TITLE
doctrine/annotations is needed

### ISSUE THREAD

**Issue by devbysb** [slope-it/breadcrumb-bundle#20]
Hi, with php8 normally we don't need [doctrine/](https://packagist.org/packages/doctrine/)annotations have you plane to remove this dependency ? (in v2)

**Comment by devbysb** [comment]
Hi, If I disable annotations to resolve all symfony 6.4 deprecations with this

in the framework.yml file 
annotations: false

The breadcrumb not working 

  The service "slope_it.breadcrumb.listener" has a dependency on a non-existent service "annotation_reader".                                              
                                       
Is an update is planned ?

**Comment by asprega** [comment]
Hi! Sorry for the late reply. Yes, I'm planning to remove support for annotations altogether. I will update this issue once completed (hopefully by the end of the year). Thanks!

**Comment by asprega** [comment]
This was released as part of 2.0.0. Thanks!
