### ISSUE TITLE
How can I pass some variables to the breadcrumb template?

### ISSUE THREAD

**Issue by semivori** [slope-it/breadcrumb-bundle#24]
How can I pass some variables to the breadcrumb template from my template twig file or from  controller?

**Comment by asprega** [comment]
Hi. What kind of variables do you need to pass? At the moment nothing except label, route and translatable params/domain can be passed to the breadcrumb item (and, in turn, to the template).

Can you please make an example to explain your use case?

**Comment by asprega** [comment]
Closing this issue as inactive for more than a month. Please feel free to open a new one (possibly with more detail) if needed.
