### ISSUE TITLE
Add `is_breadcrumb_empty` twig function

### ISSUE THREAD

**Issue by Jupi007** [slope-it/breadcrumb-bundle#6]
Hi,
I think it could be useful to have a kind of `is_breadcrumb_empty` twig function.
So we can check in our template if the breadcrumb is void.

I can do a PR if you are interested.

**Comment by asprega** [comment]
Hi! Thanks for your report. Can you make an example to make me understand in which case this is useful? I'm thinking that adding this function could be redundant as you can configure the bundle to use your own twig template and just handle empty breadcrumbs in there.

**Comment by Jupi007** [comment]
Hi,
well in my template, I need to know in an higher level than the breadcrumb itself if it will be rendered.
I have something like this:

```twig
{% if not slope_it_is_breadcrumb_empty() or block('adminBar') is not empty %}
    <div class="topBar">
        {{ slope_it_breadcrumb() }}

        {% if block('adminBar') is not empty %}
            <div class="adminBar">
                {% block adminBar %}{% endblock %}
            </div>
        {% endif %}
    </div>
{% endif %}
```

Thanks to this function, I know if I need to add the `topBar` block in my template by checking if both breadcrumb and admin are not empty.
