### ISSUE TITLE
Exclude unneeded parameters when generating route

### ISSUE THREAD

**Issue by Jupi007** [slope-it/breadcrumb-bundle#8]
The idea of the auto-filling route parameters is nice, but it can cause the addition of useless parameters like this:

```
/route/name?slug=nice-slug&id=3
```

I think add something like a new`disableAutofill` option could be useful to disable this behaviour.

**Comment by asprega** [comment]
Thanks for your report. In fact, this is an unintended behavior. I think we should consider a different fix though, and make sure to set only parameters that are actually used by the passed route. In other words, I don't think we should add a configuration parameter as the behavior you're observing is never desired. I will look into a better way to build the url by only extracting parameters used by both routes (current one and the one being built).

**Comment by Jupi007** [comment]
Okay.
I tried to patch this in a cleaner way (looking at matching parameters as you said), but I didn't found a solution.
That's why I proposed an option to disable this behaviour.

I hope you will found a better solution.
Should I close the PR?

**Comment by asprega** [comment]
I think I found a way to make it work using `RequestContext`. Give me a few days and I'll open a PR. I will let you know when it's ready :)

**Comment by Jupi007** [comment]
Very nice, thanks!

**Comment by asprega** [comment]
Hey, it was easier than expected :) I tried this in my own project and it works, can you give it a shot on your project and let me know?
You will have to require a development version of this library pointing to this branch.

In the meanwhile I would like to add some integration tests with the framework components themselves and, if everything works, I will tag a new version.

Thanks!

**Comment by Jupi007** [comment]
Awesome, I test this at once!

**Comment by Jupi007** [comment]
Thanks a lot to have fixed this :)

This bundle is really awesome, and I'm happy to see that all issues I noticed are fixed now 🥳

**Comment by asprega** [comment]
Just released 1.3.0 including this fix! I'm very glad you're finding this useful. Thanks!

**Comment by Jupi007** [comment]
Thank you very much, I'll update my project at once :)
