### ISSUE TITLE
Giving non string parameter throw an exception

### ISSUE THREAD

**Issue by Jupi007** [slope-it/breadcrumb-bundle#9]
When giving a non string route parameter like an integer to the breadcrumb builder, the app throw an exception when rendering the template.

```php
$breadcrumbBuilder->addItem(label: 'A nice label', route: 'route_name', routeParams: [
    'id' => $entity->getId(),
])
```
```
Warning: Trying to access array offset on value of type int
```

As a workaround, we can force the conversion to string locally, but as we can generate a route with any type of value in any other part of the application, I think this should be supported by the breadcrumb builder itself.

**Comment by asprega** [comment]
Hi, thanks for your report. You're right, this is a bug. Can you please re-open PR #14 so that I can merge it? Thanks!
